name: SonarQube

on:
  push:
    branches:
      - main

jobs:

  tests:

    name: Coverage

    runs-on: ubuntu-latest

    environment:
      name: main

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: xdebug

      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Coverage
        run: XDEBUG_MODE=coverage vendor/bin/pest --coverage --coverage-clover=coverage.xml

      - name: SonarQube Config
        run: |
          echo "sonar.projectKey=edersoares_composer-plug-and-play" >> sonar-project.properties
          echo "sonar.organization=edersoares" >> sonar-project.properties

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
