name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tests:

    name: Unit Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 8.1
          - 8.2
          - 8.3
        composer-version:
          - 2.3
          - 2.4
          - 2.5

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php-version }}"
        tools: "composer:${{ matrix.composer-version }}"

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: php-${{ matrix.php-version }}-composer-${{ matrix.composer-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          php-${{ matrix.php-version }}-composer-${{ matrix.composer-version }}

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer run-script test
